### PR TITLE
Update applet to be KF6 compatible

### PR DESCRIPTION
**Pull request by afontenot**
This PR makes changes to achieve compatibility with KF6 and the upcoming KDE / Plasma release, and fixes several bugs with how devices are displayed in the applet:

 * An issue where the "eject" icon is displayed for non-removable devices is fixed.
 * An issue where devices that have not been mounted are not shown is fixed.

Some lingering issues that could either be resolved as part of this PR or come later:

 * The build system specifies a required version of Plasma. I went with 5.92.0 because that's the release I'm testing on. After the 6.0.0 stable release is out, this should probably be changed to "Plasma 6" so that only the major version will be matched. (Or maybe the version could be left unspecified, since KF6 is required after all.)
 * The filters for the place type (e.g. hidden, devices, etc) rely on a `Plasma5Support.DataSource` for their `sourceModel`, but my understanding is that this approach is intended to be deprecated. It's not at all clear to me what the preferred way to do this in QML is now.
 * I see issues like the following in the log when starting plasmashell:

```
ConfigGeneral.qml: Setting initial properties failed: ConfigGeneral does not have a property called cfg_widgetWidthDefault
```

The cause of this isn't clear to me. Plasmashell appears to be trying to set properties called e.g. `cfg_widgetWidthDefault`, `cfg_showSearchesDefault`, etc, but of course these properties don't exist, the properties are called e.g. `cfg_widgetWidth`, etc. I can't figure out why it's appending "Default" to the property names. This does not appear to affect the actual functioning of the applet.

### CODE REVIEW

**Comment by afontenot** [comment]
Re this:

> It's not at all clear to me what the preferred way to do this in QML is now.

Intuitively you'd import a model like `KFilePlacesModel` from KIO, but the KIO plugin [was removed from KDeclarative](https://invent.kde.org/frameworks/kdeclarative/-/merge_requests/169), and unfortunately there's no obvious pointer on a replacement.

**Comment by dfaust** [comment]
Hey @afontenot, thank you for your work. I'll have a look at it as soon as I can.

**Comment by dfaust** [comment]
I managed to test parts of the applet and it works without issues so far.

> `ConfigGeneral.qml: Setting initial properties failed: ConfigGeneral does not have a property called cfg_widgetWidthDefault`

I don't get this message.

But I'm running it in a distrobox and d-bus isn't setup correctly. So I get:

`kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"`
 
And querying devices doesn't work.
Also I can't open the settings dialog with the new version of `plasmawindowed`.

I also tried booting [Neon](https://neon.kde.org/download) in Virtual Box - without success.

I would be fine with merging it, as it is. Hopefully I can test it more thoroughly soon.

**Comment by afontenot** [comment]
>> ConfigGeneral.qml: Setting initial properties failed: ConfigGeneral does not have a property called cfg_widgetWidthDefault

> I don't get this message.

Just to make sure we're looking at the same thing, this is in the plasmashell log. So for example I see these messages with the following command:

    journalctl --user -b --no-pager -u plasma-plasmashell | grep -i placesWidget

It's possible there could be some leftover config that got created somewhere when I was debugging the applet.

> I'm running it in a distrobox and d-bus isn't setup correctly.

I believe this is expected, then? At least I don't think any new issues are introduced by my changes.

> Also I can't open the settings dialog with the new version of `plasmawindowed`.

I see this with every applet, it appears that both `plasmawindowed` and `plasmoidviewer` are broken in quite a few ways - among others that it's not possible to access the context menu for applets, so there's no way to get to the settings for most of them.

**Comment by dfaust** [comment]
I still haven't been able to run a complete plasma session and test the widget completely, yet.
But the PR looks good, so I'm going to merge it now.
Thank you very much for your work!

**Comment by afontenot** [comment]
Great! I just noticed that there's already a Plasma 6 section on opendesktop.org - https://www.opendesktop.org/browse?cat=706&ord=latest

Would it be reasonable to make a point release and upload it there? It might get us a few testers.

Edit: or is it [store.kde.org](https://store.kde.org/browse/)? Honestly I've never used these frontends, I only install applets via distribution packages. I'm not sure how the different Pling sites are related.

**Comment by afontenot** [comment]
@dfaust just giving this a quick bump again - the KDE 6 release was today, so would it be possible to get the applet listed on as a Plasma 6 applet on https://store.kde.org/browse?cat=706&ord=latest?

Bumping the package number and tagging a release would be great as well, as it gives distribution packagers (like me) something to pin to.

**Comment by afontenot** [comment]
@dfaust Hey, just bumping this once more. Plasma 6 has been out a little while now, and it'd be great to have the applet listed.

**Comment by dfaust** [comment]
https://www.pling.com/p/2135511/

@afontenot Please let me know if it works. I still haven't been able to test it.

**Comment by afontenot** [comment]
> https://www.pling.com/p/2135511/
> 
> @afontenot Please let me know if it works. I still haven't been able to test it.

Appears to be working great for me! It doesn't yet show up in the built in widget downloader, probably because they only reindex every so often. I downloaded the Plasmoid directly and that works with no problems.

Update: it's listed now!

**Pull request merged**
